name: 도커로 ci/cd 구축

on:
  push:
    branches:
      - be-dev-gromit

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repo에 올린 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 17

      - name: applcation.yml 파일 만들기
        run: |
          pwd
          echo "${{ secrets.APPLICATION_YML }}" > ./be/src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: AWS Resource 에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t issue-tracker .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag issue-tracker ${{ steps.login-ecr.outputs.registry }}/issue-tracker:latest

      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/issue-tracker:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop issue-tracker || true
            docker rm issue-tracker || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/issue-tracker:latest
            docker run -d --name issue-tracker -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/instagram-server:latest
