name: 이슈트래커

on:
  push:
    branches:
      - be-dev-gromit

jobs:
  My-cicd-job:
    runs-on: ubuntu-latest

    steps:
      - name: 헬로월드찍기
        run: echo "Hello World!"

      - name: 여러 명령어 찍기
        run: |
          echo "my name"
          echo " is"
          echo " jonghyeok "
  
