name: Docker Compose

on:
  push:
    branches:
      - be-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name : JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: create properties
        run: touch ./be/src/main/resources/application-prod.properties
      - run: echo "${{ secrets.PROPERTIES }}" > ./be/src/main/resources/application-prod.properties
        shell: bash
        
      - name: grant gradlew
        run: |
          cd ./be
          chmod +x ./gradlew

      - name: Build with gradle
        run: |
          cd ./be
          ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to AWS
        env:
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
        
      - name: Docker image Processing
        run: |
          cd ./be
          docker build -t seondays/issue-tracker:latest .
          docker push seondays/issue-tracker:latest

      - name: SSH Processing
        uses: appleboy/ssh-action@v0.1.6
        with: 
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd issue6/be/build/libs
            sudo docker pull seondays/issue-tracker:latest
            sudo docker-compose down
            sudo docker-compose up -d
    

    
